language: python
python:
    - "3.7"
install:
    - pip install pipenv==11.0.0
    - pipenv install
    - git clone https://$GITHUB_TOKEN@github.com/soasme/sowiki.git
    - export DATA_DIR=./sowiki/tiddlers
script:
    - make dump_all
    - make travis
